### PR TITLE
@W-9294376 Update Sample_SCV_Inbound_Subflow

### PR DESCRIPTION
**Pull request by yesaiarasan**

### CODE REVIEW

**Review by sfyz — COMMENTED** [review]
Looks good. Matt can comment on technical accuracy.

**Comment by nielsenius** [comment]
Two minor comments:
- I'd recommend using this JSON formatter because the current change is removing some white space: https://jsonformatter.org/json-pretty-print
- I'd recommend adding a description to the contact flow. Just a few words to explain what it does.

**Comment by yesaiarasan** [comment]
> Two minor comments:
> 
> * I'd recommend using this JSON formatter because the current change is removing some white space: https://jsonformatter.org/json-pretty-print
> * I'd recommend adding a description to the contact flow. Just a few words to explain what it does.

Thanks Matt! I have made the edits based on your feedback. Please check.

**Review by nielsenius — APPROVED** [review]

**Comment by sfyz** [comment]
Great!

**Pull request merged**
